# CleanupTask を実行する間隔（秒単位）
cleanup:
  interval-seconds: 86400   # 24時間ごとにチェックしたい場合は 86400

# Discord 通知用 Webhook URL（削除1日前の警告に使用）
# ※ 実際の URL をここに記入してください
discord_webhook_url: "YOUR_WEBHOOK_URL_HERE"

# 通知形式："embed"（埋め込み） または "plain"（テキストのみ）
message_type: "embed"

# 保護/解除/削除ログを YAML に永続化するか
persist_logs: true
